### ISSUE TITLE
Problems with dependacy kodi 19.1

### ISSUE THREAD

**Issue by irontes** [alfa-addon/addon#1006]
With a fresh install of kodi 19.1 in Windows 10 Alfa does not install.  The following error message appears:
"**The dependency on xbmc.python version 2.25.0 could not be satisfied**." 

I tried to modify the addon.xml.  I tested to modify it with  '_**script.module.requests" version="2.25.1+matrix.1**_"'  and removed all other modules from the required addon.xml.  The installation works.  

However, if I try to include "**beautifulsoup4**" etc. (even if I change the version of the modules for example with the version in Kodi repo "**+matrix.1**" it doesn't work.

Not sure if this is a bug in Kodi or in  Alfa.

**Comment by SistemaRayoXP** [comment]
I couldn't reproduce your bug. Perhaps you could send us a log reproducing the issue?

I'm speculating that it could be a network error. A while back, we had reports of unsuccessful installs because the dependency script.module.idna was not met. It was because Kodi Official repo had issues and some users couldn't download the dependency. Maybe you can try to manually install beautifulsoup4 from https://mirrors.kodi.tv/addons/matrix/script.module.beautifulsoup4/

**Comment by irontes** [comment]
I think you are right, because I did what you suggested  and everything works.
Thanks a million for your help
