### ISSUE TITLE
welcome page

### ISSUE THREAD

**Issue by irontes** [alfa-addon/addon#1159]
Just to let you guys know the welcome page and first setup in new installation of Kodi 20 Nexus does not work.  Maybe the old simple version without forcing graphics was better.

**Comment by alfa-addon** [comment]
There was a critical error on Kodi 20 Alpha-1 that made many add-ons not to work.  Tha problem was fixed in Kodi few days later.  Please use the latest Nightly for testing: https://mirrors.kodi.tv/nightlies/windows/win64/master/

Known problems:
- On adding/updating a Series/movie in the videolibrary, the Kodi cataloging crashes on VideoScan function
