### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by edenmedia** [alfa-addon/addon#1358]
**I open this issue again because I don't know how resolve the problems with the "Welcome Page".**

The Welcome page that normally shows up only when you first install Alfa, is now always popping up each time you click something and each time you open Alfa.
I don't have any cleaning addon in my Firestick's just PVR Client and Alfa. In other devices with Android the problem is less intrusive but in any case every month or two I have to uninstall Alfa and reinstall it for the same problems.
Kindly I could know how to disable the welcome page, I would be eternally grateful.

Update:
I have disabled the following line in the "launcher" file and it seems that everything works perfectly but I'm not sure if this brings other kinds of problems
```

#    if not config.get_setting('show_once'):
#         configurator.show_window()
```

Thank you very much for any answer and advice

**Comment by SistemaRayoXP** [comment]
Look… we have a protocol to report errors. This particular error at this moment is very specific to you, and without a log made following our guides to report bugs, we can't figure out what's going on with your installation, not even considering the fact that you need to uninstall Alfa every so often is indicating a major issue.

[Steps for a correct bug report (translated)](https://alfa--addon-com.translate.goog/temas/pasos-para-un-correcto-reporte-de-error.25/?_x_tr_sl=es&_x_tr_tl=en)

By the way, similar errors have been reported in the past with the welcome page, and it's usually related to errors in storage, either because a cleaning add-on is deleting Alfa files, or because the profile data folder of the add-on has issues (it could be not writeable, corrupted, too slow or just inaccessible), I'd check that.

**Comment by edenmedia** [comment]
Hi thanks for the answer I will try to do a reset of the firestick and a clean installation of Alfa. If the same problem persists, I will post the log. Thank you
