### ISSUE TITLE
Problem with configuration News

### ISSUE THREAD

**Issue by irontes** [alfa-addon/addon#990]
Hi, 
I have noticed that it is not possible to change the settings in the "News" section (because the Configuration Section is no longer available) so I cannot switch from seeing results: "without group, grouped by channel or grouped by content".  
Is there away that this configuration setting can be placed back into the General Settings?  

Another 2 things that I have noticed and I like to let you know:
 1 -  after using Alfa for awhile is that when I go into the settings and press "CLEAR CACHE" there is no message that states if it was cleared or not but I honestly don't think it works. Is this normal or a bug?
2 - InfoPlus in Windows 10 the video suggested (TAMBIEN), Search, etc.  does not work.
Thank you

**Comment by SistemaRayoXP** [comment]
The behaviour of News you describe is intended. The general structure of the news section was heavily modified at code level (that's why the version was bumped to *.4.0), so many features incompatible with the new code were removed. The current behaviour is to group by content, and given current addon priorities this will stay as is, sorry about that.

About the issues you mention:
1. The notification not being shown is a bug, but the function actually does its job. Will be fixed in the next version.
2. It will be investigated, InfoPlus hasn't been touched in a little while

**Comment by irontes** [comment]
Hi, thank you for your response, everything is more clear now.  The only thing is believe that the 'News' whole has a bug or doesn't work well.   For example, if I choose "Movie 4k" sometimes it results as empty or comes out with very few results however,  if I go directly into the channel the list of 4k movies is much longer.  I worry that the other sections found in "News" section such as "Movie, Serie" etc. also have incomplete results just as Movie 4K that is very evident.
Thank you

**Comment by SistemaRayoXP** [comment]
This behaviour is a side effect. Unfortunately, some changes arrive without too much user notice. The "news" are now filtered in such a way that only the most recent elements are shown (that is, from the last 2 years). While this applies to all subsections of news (other sections list apparently fine, but you'll notice there aren't items older than 2020), it seems to affect the most to 4K movies (because not many 4K movies are released in Alfa's channels).

As many users were confused by this, there's something being worked on to show all news, regardless of date, but as of now it is an "intended" side effect, sorry for the inconvenience.
